[package]
name = "zep"
version = "0.1.0"
edition = "2024"
authors = ["dragonpeti dragonpeti53@gmail.com"]
description = "A minimal, super simple, async HTTP library in Rust"
license = "MIT"
repository = 

[dependencies]
tokio = { version = "1.48.0", features = ["full"] }
